apiVersion: apps/v1
kind: Deployment
metadata:
  name: auroque-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auroque
  template:
    metadata:
      labels:
        app: auroque
    spec:
      containers:
      - name: auroque
        image: auroque/auroque:latest
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: auroque-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: auroque
